import type { SkillCategory } from '@/types/skill';

/**
 * All skill categories with their respective skills
 */
export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    category: 'AI/ML',
    icon: '🤖',
    skills: [
      'LLaMA 3.2',
      'LangGraph',
      'LoRA',
      'Unsloth',
      'HuggingFace',
      'Tavily',
      'Anthropic',
      'OpenAI',
      'YOLOv8',
      'WandB',
      'RunPod',
      'MediaPipe',
      'OpenCV',
      'DeepFace',
    ],
    desktopDisplayCount: 4,
  },
  {
    category: 'Backend',
    icon: '⚙️',
    skills: [
      'FastAPI',
      'Spring Boot',
      'JWT',
      'OAuth',
      'Spring Security',
      'Spring Data JPA',
      'SSE',
      'Pydantic',
      'Selenium',
      'H2',
      'log4jdbc',
      'MyBatis',
      'Flask',
      'Gradle',
      'Oracle DB',
      'MySQL',
      'ChromaDB',
      'QDrant',
    ],
    desktopDisplayCount: 4,
  },
  {
    category: 'Frontend',
    icon: '🎨',
    skills: [
      'React',
      'TypeScript',
      'Tailwind',
      'Vite',
      'Jotai',
      'TanStack Query',
      'Axios',
      'html2Canvas',
      'jsPDF',
      'Next.js',
      'Material-UI',
      'React Router Dom',
      'Recoil',
      'Prettier',
      'Recharts',
    ],
    desktopDisplayCount: 4,
  },
  {
    category: 'Data',
    icon: '📊',
    skills: [
      'Python',
      'NumPy',
      'Pandas',
      't-SNE',
      'Matplotlib',
      'Seaborn',
      'Scikit-learn',
    ],
    desktopDisplayCount: 4,
  },
  {
    category: 'DevOps & Tools',
    icon: '🔧',
    skills: [
      'Git',
      'GitHub',
      'Notion',
      'Jira',
      'Docker',
      'AWS',
      'Vercel',
      'Postman',
      'IntelliJ',
      'PyCharm',
      'WebStorm',
      'DataGrip',
      'CursorAI',
      'Windsurf',
      'Jupyter Notebook',
      'GitHub Desktop',
      'Fork',
    ],
    desktopDisplayCount: 4,
  },
];
